const fs = require('fs');
const path = require('path');
const ROOT = __dirname;
const OUT = path.join(ROOT, 'dist');
const readJSON = p => JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));
const read = p => fs.readFileSync(path.join(ROOT,p),'utf8');
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const attr = esc;
const br = s => esc(s).replace(/\n/g,'<br>');
const wa = (phone,msg) => `https://wa.me/${String(phone).replace(/\D/g,'')}?text=${encodeURIComponent(msg)}`;
const clean = p => String(p||'').replace(/^\//,'');
const write = (name, content) => { const f=path.join(OUT,name); fs.mkdirSync(path.dirname(f),{recursive:true}); fs.writeFileSync(f,content); };
const copyDir=(src,dst)=>{ if(!fs.existsSync(src)) return; fs.mkdirSync(dst,{recursive:true}); for(const e of fs.readdirSync(src,{withFileTypes:true})){ const a=path.join(src,e.name), b=path.join(dst,e.name); e.isDirectory()?copyDir(a,b):fs.copyFileSync(a,b); }};
fs.rmSync(OUT,{recursive:true,force:true}); fs.mkdirSync(OUT,{recursive:true});
const site=readJSON('content/site.json'); const projects=readJSON('content/projects.json').projects||[];
const homeCss=read('src/home.css'); const svcCss=read('src/service.css'); const B=site.business; const W=wa(B.phone_e164,B.whatsapp_message);
const serviceFiles=['insaat-sonrasi-temizlik-mersin','fabrika-endustriyel-temizlik-mersin','kurum-is-yeri-temizligi-mersin','merdiven-ortak-alan-temizligi-mersin','bos-daire-temizligi-mersin'];
const svcData=Object.fromEntries(serviceFiles.map(n=>[n,readJSON(`content/services/${n}.json`)]));
function brand(){return `${esc(B.brand)}<small>${esc(B.brand_city)}</small>`}
function footer(){return `<footer class="footer"><div class="wrap"><div class="footer-grid"><div><div class="brand">${brand()}</div><p>${esc(B.footer_tagline)}</p></div><div><b>Hizmetler</b><p>${serviceFiles.map(n=>`<a href="${n}.html">${esc(svcData[n].label)}</a>`).join('<br>')}</p></div><div><b>İletişim</b><p><a href="tel:${attr(B.phone_e164)}">${esc(B.phone_display)}</a><br>${esc(B.city)}</p></div></div><div class="legal">${esc(B.copyright)}</div></div></footer>`}
function projectCards(){return projects.map(p=>{const alt=esc(p.alt||p.title||'Arin Temizlik Mersin proje fotoğrafı'); if(p.type==='before_after'&&p.image_before&&p.image_after) return `<article class="project-card"><div class="before-after"><figure><img src="${attr(clean(p.image_before))}" alt="${alt} öncesi" loading="lazy"><figcaption>ÖNCE</figcaption></figure><figure><img src="${attr(clean(p.image_after))}" alt="${alt} sonrası" loading="lazy"><figcaption>SONRA</figcaption></figure></div><div class="project-copy"><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p></div></article>`; if(p.image) return `<article class="project-card"><img src="${attr(clean(p.image))}" alt="${alt}" loading="lazy"><div class="project-copy"><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p></div></article>`; return ''}).join('\n')}
function home(){ const S=site.services_section, H=site.hero, F=site.featured, P=site.process, A=site.about, Q=site.faq, C=site.contact; const schema={"@context":"https://schema.org","@type":"LocalBusiness","name":B.business_name,"url":"https://arintemizlikmersin.com/","telephone":B.phone_e164,"description":site.seo.description,"areaServed":{"@type":"City","name":B.city},"hasOfferCatalog":{"@type":"OfferCatalog","name":"Temizlik Hizmetleri","itemListElement":S.items.map(x=>({"@type":"Offer","itemOffered":{"@type":"Service","name":x.title}}))}};
return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(site.seo.title)}</title><meta name="description" content="${attr(site.seo.description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="https://arintemizlikmersin.com/"><meta name="theme-color" content="#0c2237"><meta property="og:locale" content="tr_TR"><meta property="og:type" content="website"><meta property="og:title" content="${attr(site.seo.social_title)}"><meta property="og:description" content="${attr(site.seo.social_description)}"><meta property="og:url" content="https://arintemizlikmersin.com/"><meta property="og:site_name" content="${attr(B.business_name)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${attr(site.seo.social_title)}"><meta name="twitter:description" content="${attr(site.seo.social_description)}"><script type="application/ld+json">${JSON.stringify(schema)}</script><style>${homeCss}\n.visual{background-image:url("${attr(clean(H.image))}")} .featured-card{background-image:url("${attr(clean(F.image))}")}</style></head><body>
<header><div class="wrap"><nav><div class="brand">${brand()}</div><div class="links"><a href="#hizmetler">Hizmetler</a><a href="#surec">Nasıl Çalışıyoruz?</a><a href="#hakkimizda">Hakkımızda</a><a href="#projeler">Projeler</a><a href="#sss">S.S.S.</a></div><a class="contact" href="#iletisim">İletişime Geç</a></nav></div></header><main>
<div class="hero"><div class="hero-copy"><div class="eyebrow">${esc(H.eyebrow)}</div><h1>${br(H.title)}</h1><p>${esc(H.description)}</p><div class="actions"><a class="btn primary" href="#surec">${esc(H.primary_button)}</a><a class="btn secondary" href="#iletisim">${esc(H.secondary_button)}</a></div></div><div class="visual"><div class="visual-card"><b>${esc(H.image_card_title)}</b><span>${esc(H.image_card_text)}</span></div></div></div>
<section id="hizmetler"><div class="wrap"><div class="section-head"><div><div class="eyebrow">${esc(S.eyebrow)}</div><h2>${esc(S.title)}</h2></div><p>${esc(S.description)}</p></div><div class="services">${S.items.map((x,i)=>`<article class="service"><span class="num">${String(i+1).padStart(2,'0')}</span><h3><a href="${attr(x.url)}">${esc(x.title)}</a></h3><p>${esc(x.description)}</p><a class="service-link" href="${attr(x.url)}">Hizmeti incele →</a></article>`).join('')}</div></div></section>
<section class="featured"><div class="wrap"><div class="featured-grid"><div><div class="featured-card" role="img" aria-label="${attr(F.caption)}"></div><div class="caption">${esc(F.caption)}</div></div><div class="featured-copy"><div class="eyebrow">${esc(F.eyebrow)}</div><h2>${br(F.title)}</h2>${F.paragraphs.map(x=>`<p>${esc(x)}</p>`).join('')}<div class="ticks">${F.bullets.map((x,i)=>`<div class="tick"><span>${String(i+1).padStart(2,'0')}</span> ${esc(x)}</div>`).join('')}</div></div></div></div></section>
<section class="process" id="surec"><div class="wrap"><div class="section-head"><div><div class="eyebrow">${esc(P.eyebrow)}</div><h2>${esc(P.title)}</h2></div><p>${esc(P.description)}</p></div><div class="steps">${P.steps.map((x,i)=>`<div class="step"><strong>${i+1}</strong><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p></div>`).join('')}</div><div class="note"><b>${esc(P.note_title)}</b> ${esc(P.note_text)}</div></div></section>
<section id="hakkimizda"><div class="wrap"><div class="about-grid"><div><div class="eyebrow">${esc(A.eyebrow)}</div><h2>${esc(A.title)}</h2></div><div class="about-copy">${A.paragraphs.map(x=>`<p>${esc(x)}</p>`).join('')}<div class="promise">${esc(A.promise)}</div></div></div></div></section>
<section id="projeler"><div class="wrap"><div class="section-head"><div><div class="eyebrow">${esc(site.projects_section.eyebrow)}</div><h2>${esc(site.projects_section.title)}</h2></div><p>${esc(site.projects_section.description)}</p></div><div class="projects" id="projects-grid">${projectCards()}</div></div></section>
<section class="faq" id="sss"><div class="wrap"><div class="section-head"><div><div class="eyebrow">${esc(Q.eyebrow)}</div><h2>${esc(Q.title)}</h2></div><p>${esc(Q.description)}</p></div><div class="faq-list">${Q.items.map(x=>`<details><summary>${esc(x.question)}</summary><p>${esc(x.answer)}</p></details>`).join('')}</div></div></section>
<section class="cta" id="iletisim"><div class="wrap"><div class="eyebrow">${esc(C.eyebrow)}</div><h2>${esc(C.title)}</h2><p>${esc(C.description)}</p><div class="actions"><a class="btn primary" href="tel:${attr(B.phone_e164)}">${esc(C.call_button)}: ${esc(B.phone_display)}</a><a class="btn secondary" href="${attr(W)}" target="_blank" rel="noopener">${esc(C.whatsapp_button)}</a></div><p class="micro">${esc(C.micro)}</p></div></section></main>${footer()}<a class="wa-float" href="${attr(W)}" target="_blank" rel="noopener">WhatsApp</a></body></html>`}
function servicePage(slug,d){const url=`https://arintemizlikmersin.com/${slug}.html`; const schema={"@context":"https://schema.org","@type":"Service","name":d.h1,"provider":{"@type":"LocalBusiness","name":B.business_name,"url":"https://arintemizlikmersin.com/","telephone":B.phone_e164},"areaServed":{"@type":"City","name":B.city},"url":url,"description":d.seo_description}; const related=serviceFiles.filter(x=>x!==slug).map(x=>`<a href="${x}.html">${esc(svcData[x].label)}</a>`).join(''); const faq=d.faq||[];
return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(d.seo_title)}</title><meta name="description" content="${attr(d.seo_description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${attr(url)}"><meta name="theme-color" content="#0c2237"><meta property="og:locale" content="tr_TR"><meta property="og:type" content="website"><meta property="og:title" content="${attr(d.seo_title)}"><meta property="og:description" content="${attr(d.seo_description)}"><meta property="og:url" content="${attr(url)}"><meta property="og:site_name" content="${attr(B.business_name)}"><script type="application/ld+json">${JSON.stringify(schema)}</script><style>${svcCss}</style></head><body><header><div class="wrap"><nav><a class="brand" href="index.html">${brand()}</a><div class="navlinks"><a href="index.html#hizmetler">Hizmetler</a><a href="index.html#surec">Nasıl Çalışıyoruz?</a><a href="index.html#projeler">Projeler</a><a href="index.html#sss">S.S.S.</a></div><a class="contact" href="index.html#iletisim">İletişime Geç</a></nav></div></header><main>
<section class="hero"><div class="wrap"><div class="hero-grid"><div><div class="eyebrow">${esc(d.eyebrow)}</div><h1>${esc(d.h1)}</h1><p>${esc(d.intro)}</p><div class="actions"><a class="btn primary" href="tel:${attr(B.phone_e164)}">Ara: ${esc(B.phone_display)}</a><a class="btn secondary" href="${attr(W)}" target="_blank" rel="noopener">WhatsApp'tan Ulaş</a></div></div><img src="${attr(clean(d.hero_image))}" alt="${attr(d.hero_alt)}"></div></div></section>
<section><div class="wrap"><div class="content-grid"><div class="copy"><h2>${esc(d.section_title)}</h2>${(d.blocks||[]).map(x=>`<h3>${esc(x.heading)}</h3><p>${esc(x.body)}</p>`).join('')}</div><aside class="side"><h2>${esc(d.scope_title)}</h2><ul>${(d.scope||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p style="margin-top:20px;color:#66727d;line-height:1.7;font-size:14px">${esc(d.scope_note)}</p></aside></div></div></section>
${faq.length?`<section><div class="wrap"><h2>${esc(d.label)} Hakkında Sık Sorulan Sorular</h2>${faq.map(x=>`<h3>${esc(x.question)}</h3><p>${esc(x.answer)}</p>`).join('')}</div></section>`:''}
<section class="related"><div class="wrap"><div class="eyebrow">Diğer hizmetler</div><h2 style="font-size:34px;margin:10px 0 28px">${esc(B.business_name)} hizmetleri</h2><div class="related-grid">${related}</div></div></section>
<section class="cta"><div class="wrap"><div class="eyebrow">İletişim</div><h2>${esc(site.contact.title)}</h2><p>Alanı yerinde görebilir veya uygun durumlarda WhatsApp üzerinden video ve fotoğrafları inceleyebiliriz. İşin kapsamı netleştikten sonra fiyatlandırma yapılır.</p><div class="actions"><a class="btn primary" style="background:#c9a35c;color:#081a2b" href="tel:${attr(B.phone_e164)}">${esc(B.phone_display)}</a><a class="btn secondary" href="index.html#iletisim">İletişim bölümüne git</a></div></div></section></main>${footer()}</body></html>`}
write('index.html',home()); for(const slug of serviceFiles) write(`${slug}.html`,servicePage(slug,svcData[slug]));
for(const f of ['robots.txt','sitemap.xml']) if(fs.existsSync(path.join(ROOT,f))) fs.copyFileSync(path.join(ROOT,f),path.join(OUT,f)); copyDir(path.join(ROOT,'admin'),path.join(OUT,'admin')); copyDir(path.join(ROOT,'images'),path.join(OUT,'images')); copyDir(path.join(ROOT,'content'),path.join(OUT,'content'));
console.log('Site oluşturuldu: dist/');
